local M = {}

local function set(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

function M.apply()
  -- Contextual bracket-depth overlays.
  set("KonsoleBreezeNestedBracket", { fg = "#A6E3A1" })
  set("KonsoleBreezeTertiaryBracket", { fg = "#3DAEE9", bold = true })
  set("KonsoleBreezeStringBracket", { fg = "#CDD6F4" })
  set("KonsoleBreezeTypeCast", { fg = "#6B3FA0", bold = true })
  set("KonsoleBreezeReadUse", { fg = "#A6E3A1" })
  set("KonsoleBreezeDynamicRead", { fg = "#D2B48C" })
  set("KonsoleBreezeStringVariable", { fg = "#A6E3A1" })
  set("KonsoleBreezeImportTarget", { fg = "#A6E3A1" })

  -- Treesitter
  set("@comment", { fg = "#9399B2", italic = true })
  set("@string", { fg = "#CDD6F4" })
  set("@string.regex", { fg = "#1abc9c" })
  set("@string.escape", { fg = "#3DAEE9" })
  set("@number", { fg = "#FAB387" })
  set("@boolean", { fg = "#D2B48C" })
  set("@constant", { fg = "#CBA6F7" })
  set("@constant.builtin", { fg = "#CBA6F7" })
  set("@type", { fg = "#CBA6F7" })
  set("@type.builtin", { fg = "#CBA6F7" })
  set("@type.cast", { fg = "#6B3FA0", bold = true })
  set("@constructor", { fg = "#CBA6F7" })
  set("@module", { fg = "#A6E3A1" })
  set("@module.builtin", { fg = "#A6E3A1" })
  set("@namespace", { fg = "#A6E3A1" })
  set("@include", { fg = "#3DAEE9", bold = true })
  set("@function", { fg = "#CBA6F7" })
  set("@function.builtin", { fg = "#CBA6F7" })
  set("@function.call", { fg = "#CBA6F7" })
  set("@function.method", { fg = "#CBA6F7" })
  set("@function.method.call", { fg = "#CBA6F7" })
  set("@keyword", { fg = "#3DAEE9", bold = true })
  set("@keyword.return", { fg = "#3DAEE9", bold = true })
  set("@keyword.operator", { fg = "#3DAEE9", bold = true })
  set("@operator", { fg = "#CDD6F4" })
  set("@property", { fg = "#EBA0AC" })
  set("@variable", { fg = "#EBA0AC" })
  set("@variable.member", { fg = "#EBA0AC" })
  set("@variable.parameter", { fg = "#A6E3A1" })
  set("@parameter", { fg = "#A6E3A1" })
  set("@parameter.reference", { fg = "#A6E3A1" })
  set("@variable.builtin", { fg = "#EBA0AC" })
  set("@variable.assignment", { fg = "#EBA0AC" })
  set("@variable.member.assignment", { fg = "#EBA0AC" })
  set("@property.assignment", { fg = "#EBA0AC" })
  set("@punctuation.delimiter", { fg = "#FFFFFF" })
  set("@punctuation.bracket", { fg = "#1ABC9C" })
  set("@punctuation.special", { fg = "#FFFFFF" })
  set("@string.delimiter", { fg = "#3DAEE9" })

  -- LSP semantic tokens
  set("@lsp.type.type", { fg = "#CBA6F7" })
  set("@lsp.type.type.cast", { fg = "#6B3FA0", bold = true })
  set("@lsp.type.class", { fg = "#CBA6F7" })
  set("@lsp.type.enum", { fg = "#CBA6F7" })
  set("@lsp.type.interface", { fg = "#CBA6F7" })
  set("@lsp.type.struct", { fg = "#CBA6F7" })
  set("@lsp.type.namespace", { fg = "#A6E3A1" })
  set("@lsp.type.parameter", { fg = "#A6E3A1" })
  set("@lsp.type.property", { fg = "#A6E3A1" })
  set("@lsp.type.variable", { fg = "#A6E3A1" })
  set("@lsp.type.function", { fg = "#CBA6F7" })
  set("@lsp.type.method", { fg = "#CBA6F7" })
  set("@lsp.type.keyword", { fg = "#3DAEE9", bold = true })
  set("@lsp.type.boolean", { fg = "#D2B48C" })
  set("@lsp.type.enumMember", { fg = "#FAB387" })
  set("@lsp.type.decorator", { fg = "#CBA6F7" })

  set("@lsp.mod.readonly", { italic = true })
  set("@lsp.mod.declaration", { fg = "#EBA0AC" })
  set("@lsp.mod.definition", { fg = "#EBA0AC" })
  set("@lsp.mod.defaultLibrary", { fg = "#3DAEE9" })
  set("@lsp.mod.deprecated", { strikethrough = true })

  -- General read/write model: declarations/definitions are write-side (rose).
  set("@lsp.typemod.variable.declaration", { fg = "#EBA0AC" })
  set("@lsp.typemod.variable.definition", { fg = "#EBA0AC" })
  set("@lsp.typemod.variable.globalScope", { fg = "#EBA0AC" })
  set("@lsp.typemod.variable.fileScope", { fg = "#EBA0AC" })
  set("@lsp.typemod.variable.static", { fg = "#EBA0AC" })
  set("@lsp.typemod.variable.readonly", { fg = "#A6E3A1", italic = true })
  set("@lsp.typemod.parameter.declaration", { fg = "#EBA0AC" })
  set("@lsp.typemod.property.declaration", { fg = "#EBA0AC" })

  -- Keep callable declarations lavender even when declaration/definition mod is present.
  set("@lsp.typemod.function.declaration", { fg = "#CBA6F7" })
  set("@lsp.typemod.function.definition", { fg = "#CBA6F7" })
  set("@lsp.typemod.method.declaration", { fg = "#CBA6F7" })
  set("@lsp.typemod.method.definition", { fg = "#CBA6F7" })
  set("@lsp.typemod.class.declaration", { fg = "#CBA6F7" })
  set("@lsp.typemod.class.definition", { fg = "#CBA6F7" })
  set("@lsp.typemod.type.declaration", { fg = "#CBA6F7" })
  set("@lsp.typemod.type.definition", { fg = "#CBA6F7" })
  set("@lsp.typemod.interface.declaration", { fg = "#CBA6F7" })
  set("@lsp.typemod.interface.definition", { fg = "#CBA6F7" })
  set("@lsp.typemod.struct.declaration", { fg = "#CBA6F7" })
  set("@lsp.typemod.struct.definition", { fg = "#CBA6F7" })
  set("@lsp.typemod.enum.declaration", { fg = "#CBA6F7" })
  set("@lsp.typemod.enum.definition", { fg = "#CBA6F7" })
  set("@type.definition", { fg = "#CBA6F7" })
  set("@lsp.typemod.type.cast", { fg = "#6B3FA0", bold = true })
end

return M
